servingEngineSpec:
  runtimeClassName: ""
  enableKubeRay: true
  modelSpec:
  - name: "distilgpt2"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "distilbert/distilgpt2"

    replicaCount: 2

    requestCPU: 6
    requestMemory: "16Gi"
    requestGPU: 1

    vllmConfig:
      tensorParallelSize: 1
      pipelineParallelSize: 2
