{{- if and .Values.servingEngineSpec.enableEngine .Values.servingEngineSpec.enableKubeRay }}
{{- range $modelSpec := .Values.servingEngineSpec.modelSpec }}
{{- with $ -}}
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: "{{ .Release.Name }}-{{$modelSpec.name}}-raycluster-vllm"
  namespace: {{ .Release.Namespace }}
  labels:
    helm-release-name: {{ .Release.Name }}
spec:
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: "0.0.0.0"
    template:
      metadata:
        labels:
          model: {{ $modelSpec.name }}
          {{- include "chart.engineLabels" . | nindent 10 }}
      spec:
        terminationGracePeriodSeconds: 0
        {{- if .Values.servingEngineSpec.securityContext }}
        securityContext:
          {{- toYaml .Values.servingEngineSpec.securityContext | nindent 8 }}
        {{- end }}
        containers:
          - name: vllm-ray-head
            image: "{{ required "Required value 'modelSpec.repository' must be defined !" $modelSpec.repository }}:{{ required "Required value 'modelSpec.tag' must be defined !" $modelSpec.tag }}"
            livenessProbe:
              exec:
                command: ["/bin/bash", "-c", "echo TBD"]
            readinessProbe:
              exec:
                command: ["/bin/bash", "-c", "echo TBD"]
  workerGroupSpecs:
    - rayStartParams: {}
      replicas: {{ $modelSpec.replicaCount }}
      groupName: vllm-ray-worker
      template:
        {{- if .Values.servingEngineSpec.securityContext }}
        securityContext:
          {{- toYaml .Values.servingEngineSpec.securityContext | nindent 8 }}
        {{- end }}
        spec:
          containers:
            - name: vllm-ray-worker
              image: "{{ required "Required value 'modelSpec.repository' must be defined !" $modelSpec.repository }}:{{ required "Required value 'modelSpec.tag' must be defined !" $modelSpec.tag }}"
              resources:
                limits:
                  nvidia.com/gpu: {{ .Values.servingEngineSpec.gpuLimit }}
              livenessProbe:
                exec:
                  command: ["/bin/bash", "-c", "echo TBD"]
              readinessProbe:
                exec:
                  command: ["/bin/bash", "-c", "echo TBD"]


{{- if and $modelSpec.chatTemplate (hasKey $modelSpec "chatTemplateConfigMap") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-{{$modelSpec.name}}-chat-templates"
  namespace: "{{ .Release.Namespace }}"
data:
  {{ $modelSpec.chatTemplate }}: |-
    {{ $modelSpec.chatTemplateConfigMap }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
